<?php
/**
 * ****************************************************************************
 * marquee - MODULE FOR XOOPS
 * Copyright (c) Hervé Thouzard (http://www.herve-thouzard.com)
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright       Michael Albertsen (culex)
 * @license         http://www.fsf.org/copyleft/gpl.html GNU public license
 * @package         XoopSecure
 * @author 			Michael Albertsen (http://www.culex.dk)
 * @version		    $Id $
 * ****************************************************************************
 */

if (!defined('XOOPS_ROOT_PATH')) {
	die('XOOPS root path not defined');	
}

require_once XOOPS_ROOT_PATH . '/modules/xoopssecure/include/functions.php';
include_once XOOPS_ROOT_PATH . '/modules/xoopssecure/class/scan.php';

$moduleDirName = basename( dirname( __FILE__ ) ) ;
$scan = new xoopsSecure_scan;

$modversion['name'] = _MI_XOOPSSECURE_NAME;
$modversion['version'] = '1.00';
$modversion['description'] = _MI_XOOPSSECURE_DESC;
$modversion['credits'] = "Mamba";
$modversion['author'] = 'Michael Albertsen';
$modversion['nickname'] = 'culex';
$modversion['help'] = 'page=help';
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['official'] = 0;
$modversion['image'] = 'assets/images/xoopssecure_slogo.png';
$modversion['dirname'] = 'xoopsSecure';
$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16'] = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = '../../Frameworks/moduleclasses/icons/32';

//about
$modversion['release_date']     = '2013/10/25';
$modversion["module_website_url"] = "www.xoops.org/";
$modversion["module_website_name"] = "XOOPS";
$modversion["module_status"] = "RC";
$modversion["author_website_url"] = "http://www.culex.dk";
$modversion["author_website_name"] = "Michael Albertsen";
$modversion['min_php']='5.3';
$modversion['min_xoops']="2.5.6";
$modversion['min_admin']='1.1';
$modversion['min_db']= array(
    'mysql'     => '5.0.7', 
    'mysqli'    => '5.0.7'
);

//update
//$modversion['onUpdate'] = 'include/update.php';

// SQL Tables
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
$modversion['tables'][0] = 'xoopsecure_files';
$modversion['tables'][1] = 'xoopsecure_issues';
$modversion['tables'][2] = 'xoopsecure_ignores';
$modversion['tables'][3] = 'xoopsecure_scandates';

// Admin menu
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';
$modversion['hasMain'] = 0;
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Search
$modversion['hasSearch'] = 0;

// Smarty
$modversion['use_smarty'] = 1;

// Templates
/* $i = 1;
$modversion['templates'][$i]['file'] = 'xoopssecure_run.tpl';
$modversion['templates'][$i]['description'] = ''; */
/*$i++;
$modversion['templates'][$i]['file'] = 'smallworld_userprofile_template.html';
$modversion['templates'][$i]['description'] = '';
*/

// Options
/**
 * Display date format
 */
$i = 0;
$os = getenv("OS");
$modrw = xoopssecure_apachemodule( $val = 'mod_rewrite' );
$iswin = xoopssecure_iswin();

$modversion['config'][$i]['name'] = 'break1';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_GENERALCONFIG_TITLE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'line_break';
$modversion['config'][$i]['valuetype'] = 'textbox';
$modversion['config'][$i]['default'] = 'head';

$i++;
$modversion['config'][$i]['name'] = 'dateformat';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_DATEFORMAT';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_DATEFORMAT_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'd-m-Y H:i:s';

$i++;
$modversion['config'][$i]['name'] = 'extensions';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_EXTENSIONS';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_EXTENSIONS_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'php|php3|php4|php5|phps|html|htaccess|gif|js|css';

$i++;
$modversion['config'][$i]['name'] = 'urltoscan';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_URLTOSCAN';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_URLTOSCAN_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = XOOPS_ROOT_PATH;

$i++;
$modversion['config'][$i]['name'] = 'ignorelangfile';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_IGNORELANGFILE';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_IGNORELANGFILE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0';

$i++;
$modversion['config'][$i]['name'] = 'break2';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_DEVELOPERCONFIGS_TITLE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'line_break';
$modversion['config'][$i]['valuetype'] = 'textbox';
$modversion['config'][$i]['default'] = 'head';

$i++;
$modversion['config'][$i]['name'] = 'checkstylestyle';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_CSSTYLE_TITLE';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_CSSTYLE_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = 'Xoops';
$modversion['config'][$i]['options'] = array (
                                        _MI_XOOPSSECURE_CFCHOOSE_PEAR => 'PEAR', 
                                        _MI_XOOPSSECURE_CFCHOOSE_XOOPS => 'Xoops', 
                                        _MI_XOOPSSECURE_CFCHOOSE_ZEND => 'Zend'
                                    );

$i++;
$modversion['config'][$i]['name'] = 'auto_indexfiles';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_AUTOINDEXFILES';
$modversion['config'][$i]['description'] = ($modrw['exists'] == 1) ? '_MI_XOOPSSECURE_AUTOINDEXFILES_DESC':'_MI_XOOPSSECURE_AUTOINDEXFILESNO_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0';


$i++;
$modversion['config'][$i]['name'] = 'indexfiletypes';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_AUTOINDEXFILESSELECT';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_AUTOINDEXFILESSELECT_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '1';
$modversion['config'][$i]['options'] = xoopssecure_modversion_apachemod ();

$i++;
$modversion['config'][$i]['name'] = 'contentofhtmlindex';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_CONTENTOFHTMLINDEX';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_CONTENTOFHTMLINDEX_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'string';
$modversion['config'][$i]['default'] = '<script><br>history.go(-1);<br></script>';

$i++;
$modversion['config'][$i]['name'] = 'contentofhtaccessindex';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_CONTENTOFHTACCESSINDEX';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_CONTENTOFHTACCESSINDEX_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'string';
$modversion['config'][$i]['default'] = 'RewriteEngine On<br># disable directory browsing<br>Options All -Indexes';

$i++;
$modversion['config'][$i]['name'] = 'autofileperm';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_AUTOFILEPERM';
$modversion['config'][$i]['description'] = ( $iswin = false ) ? '_MI_XOOPSSECURE_AUTOFILEPERM_DESC':'_MI_XOOPSSECURE_AUTOFILEPERMWIN_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = '0';
$modversion['config'][$i]['options'] = ($iswin = false) ? array (_NO => 0 , _YES => 1 ) : array (_NO => 0);

$i++;
$modversion['config'][$i]['name'] = 'logphpmysqlissues';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_LOGPHPMYSQLISSUES';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_LOGPHPMYSQLISSUES_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0';

$i++;
$modversion['config'][$i]['name'] = 'break2';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_FULLSCANCONFIGS_TITLE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'line_break';
$modversion['config'][$i]['valuetype'] = 'textbox';
$modversion['config'][$i]['default'] = 'head';

$i++;
$obj = $scan->malwareWordstrings ();
$modversion['config'][$i]['name'] = 'fullscansfunctionsearch';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_FULLSCANFUNCTIONSEARCH_TITLE';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_FULLSCANFUNCTIONSEARCH_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'string';
$modversion['config'][$i]['default'] = xoopssecure_ArrayToString($obj);

$i++;
$obj = $scan->mallwareStrings ();
$modversion['config'][$i]['name'] = 'fullscansbadboysearch';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_FULLSCANBADBOYSSEARCH_TITLE';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_FULLSCANBADBOYSSEARCH_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'string';
$modversion['config'][$i]['default'] = xoopssecure_ArrayToString($obj);    

$i++;
$modversion['config'][$i]['name'] = 'break2';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_CRONSCANCONFIGS_TITLE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'line_break';
$modversion['config'][$i]['valuetype'] = 'textbox';
$modversion['config'][$i]['default'] = 'head';

$i++;
$modversion['config'][$i]['name'] = 'cronschedulehours';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_CRONSCAN_INTERVAL_TITLE';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_CRONSCAN_INTERVAL_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = 0;
$modversion['config'][$i]['options'] = array (
                                        _MI_XOOPSSECURE_CONFIG_ALWAYS => 0,
                                        '12'._MI_XOOPSSECURE_CONFIG_HOURS => 43200, 
                                        '1'._MI_XOOPSSECURE_CONFIG_DAY => 86400, 
                                        '2'._MI_XOOPSSECURE_CONFIG_DAYS => 172800, 
                                        '3'._MI_XOOPSSECURE_CONFIG_DAYS => 259200, 
                                        '4'._MI_XOOPSSECURE_CONFIG_DAYS => 345600, 
                                        '5'._MI_XOOPSSECURE_CONFIG_DAYS => 432000, 
                                        '6'._MI_XOOPSSECURE_CONFIG_DAYS => 518400, 
                                        '7'._MI_XOOPSSECURE_CONFIG_DAYS => 604800, 
                                        '2'._MI_XOOPSSECURE_CONFIG_WEEKS => 1209600,
                                        '1'._MI_XOOPSSECURE_CONFIG_MONTH => 2419200
                                    );
									
$i++;
$modversion['config'][$i]['name'] = 'break2';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_BACKUP_TITLE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'line_break';
$modversion['config'][$i]['valuetype'] = 'textbox';
$modversion['config'][$i]['default'] = 'head';					


$i++;
$modversion['config'][$i]['name'] = 'backuptype';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_BACKUPSELECTTYPE_TITLE';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_BACKUPSELECTTYPE_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = 'Minimum';
$modversion['config'][$i]['options'] = array (
                                        _MI_XOOPSSECURE_NONE => 'none',
										_MI_XOOPSSECURE_MIN => 'Minimum', 
										_MI_XOOPSSECURE_FULL => 'Full',
                                        _MI_XOOPSSECURE_CUSTOM => 'Custom'
                                    );		

$i++;
$obj = xoopssecure_backupFilesMin ();
$modversion['config'][$i]['name'] = 'backupcustomfiles';
$modversion['config'][$i]['title'] = '_MI_XOOPSSECURE_BACKUPCUSTOMFILES_TITLE';
$modversion['config'][$i]['description'] = '_MI_XOOPSSECURE_BACKUPCUSTOMFILES_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'string';
$modversion['config'][$i]['default'] = xoopssecure_ArrayToString($obj);  									

?>